[workspace]
resolver = "2"
members = [
    "manager"
]
exclude = [
    "mods/",
    "wamr-rust-sdk",
]

[workspace.dependencies]
wamr-rust-sdk = { path = "./wamr-rust-sdk" }

[package]
name = "wamr-mods"
version = "0.1.0"
edition = "2024"

[dependencies]
wamr-rust-sdk.workspace = true
